CREATE TABLE USER (
    ID IDENTITY NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (ID)

);

CREATE TABLE ROLE (
    ID IDENTITY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY (ID)
);


CREATE TABLE USER_ROLE (
    USER_ID BIGINT,
    ROLE_ID BIGINT,
    CONSTRAINT USER_ROLE_FK FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    CONSTRAINT ROLE_USER_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);


INSERT INTO ROLE (NAME) VALUES
    ('ADMIN'),
    ('USER');