CREATE TABLE IF NOT EXISTS DAYS_TO_ACHIEVE(
ID INT PRIMARY KEY AUTO_INCREMENT,
DAYS INT
);


INSERT INTO DAYS_TO_ACHIEVE (ID, DAYS)
VALUES (1, 12);

ALTER TABLE TODO
ADD COLUMN DAYS_TO_ACHIEVE_ID INT;

UPDATE TODO
SET DAYS_TO_ACHIEVE_ID = 1;

ALTER TABLE TODO
ADD CONSTRAINT FK_DAYS_TO_ACHIEVE_TODO FOREIGN KEY (DAYS_TO_ACHIEVE_ID) REFERENCES DAYS_TO_ACHIEVE(ID);

